FROM puckel/docker-airflow:1.10.4

ARG AIRFLOW_USER_HOME=/usr/local/airflow
ENV PYTHONPATH=$PYTHONPATH:${AIRFLOW_USER_HOME}

# Python packages required for th Selenium Plugin
USER root

RUN pip install docker && \
    pip install selenium && \
    pip install bs4 && \
    pip install lxml && \
    pip install boto3 && \
    pip install flask-bcrypt && \
    pip install werkzeug>=0.15.0 && \
    pip install pysmb==1.1.27 && \
    pip install xlrd==1.2.0 && \
    pip install python-slugify==3.0.4

RUN groupadd --gid 999 docker \
   && usermod -aG docker airflow 
USER airflow

RUN mkdir downloads