# -*- coding: utf-8 -*-
from datetime import datetime
id_code = str(datetime.now())
id_code = id_code.replace('-','').replace(':','').replace('.','').replace(' ','')

DROP_TABLE = """
DROP TABLE IF EXISTS _FORNECEDOR;
DROP TABLE IF EXISTS _FORNECEDOR_COMPLEMENTO;
DROP TABLE IF EXISTS _SERVIDOR;
DROP TABLE IF EXISTS _FORNECEDOR_SOCIO;
DROP TABLE IF EXISTS _SOCIO;
DROP TABLE IF EXISTS _FORNECEDOR_PENALIDADE;
DROP TABLE IF EXISTS _FORNECEDOR_INDICADORES;
DROP TABLE IF EXISTS _FORNECEDOR_PENALIDADE_SOCIO;
DROP TABLE IF EXISTS _FORNECEDOR_PENALIDADE_FORN;
"""


_FORNECEDOR =  """
CREATE TABLE seges_cgial_fornecedor.dbo._FORNECEDOR (
	ID_PESSOA bigint NOT NULL,
	ID_FORNECEDOR varchar(50) COLLATE Latin1_General_CI_AS NOT NULL,
	NU_CNPJ_CPF varchar(50) COLLATE Latin1_General_CI_AS NULL,
	ID_FORNECEDOR_PROPRIETARIO bigint NULL,
	ID_ENDERECO bigint NULL,
	ID_CIDADE bigint NULL,
	NO_FORNECEDOR nvarchar(300) COLLATE Latin1_General_CI_AS NULL,
	NO_FANTASIA nvarchar(300) COLLATE Latin1_General_CI_AS NULL,
	DT_ABERTURA date NULL,
	CO_SITUACAO_RFB int NULL,
	DDD nvarchar(4) COLLATE Latin1_General_CI_AS NULL,
	TELEFONE nvarchar(24) COLLATE Latin1_General_CI_AS NULL,
	DDD_ALTERNATIVO nvarchar(4) COLLATE Latin1_General_CI_AS NULL,
	TELEFONE_ALTERNATIVO nvarchar(24) COLLATE Latin1_General_CI_AS NULL,
	EMAIL nvarchar(230) COLLATE Latin1_General_CI_AS NULL,
	BAIRRO nvarchar(100) COLLATE Latin1_General_CI_AS NULL,
	LOGRADOURO nvarchar(255) COLLATE Latin1_General_CI_AS NULL,
	NUMERO_ENDERECO nvarchar(12) COLLATE Latin1_General_CI_AS NULL,
	COMPLEMENTO_ENDERECO nvarchar(255) COLLATE Latin1_General_CI_AS NULL,
	CEP bigint NULL,
	UF nvarchar(4) COLLATE Latin1_General_CI_AS NULL,
	CIDADE nvarchar(120) COLLATE Latin1_General_CI_AS NULL,
	TIPO_FORNECEDOR varchar(20) COLLATE Latin1_General_CI_AS NULL,
	ID_CONJUGE bigint NULL,
	CONSTRAINT PK_ID_FORNECEDOR_{0} PRIMARY KEY (ID_PESSOA,ID_FORNECEDOR)
);
""".format(id_code)

_FORNECEDOR_COMPLEMENTO="""
CREATE TABLE seges_cgial_fornecedor.dbo._FORNECEDOR_COMPLEMENTO (
	ID_FORN_SICAF bigint NOT NULL,
	ID_PESSOA float NULL,
	ID_RESPONSAVEL_CADASTRO float NULL,
	DT_VALIDADE_BALANCO datetime NULL,
	DT_CADASTRO datetime NULL,
	DT_ULTIMA_ATUALIZACAO datetime NULL,
	DT_VENCIMENTO_CREDENCIAMENTO datetime NULL,
	DT_VALIDADE_CREDENCIAMENTO datetime NULL,
	ID_TIPO_FORNECEDOR bigint NULL,
	TIPO_FORNECEDOR varchar(MAX) COLLATE Latin1_General_CI_AS NULL,
	CO_INSCRICAO_ESTADUAL varchar(MAX) COLLATE Latin1_General_CI_AS NULL,
	CO_INSCRICAO_MUNICIPAL varchar(MAX) COLLATE Latin1_General_CI_AS NULL,
	VL_CAPITAL_SOCIAL float NULL,
	ID_CNAE float NULL,
	CNAE varchar(MAX) COLLATE Latin1_General_CI_AS NULL,
	ID_PORTE_EMPRESA float NULL,
	PORTE_EMPRESA varchar(MAX) COLLATE Latin1_General_CI_AS NULL,
	STATUS varchar(MAX) COLLATE Latin1_General_CI_AS NULL,
	EXISTE_PEND_NIVEL1 varchar(MAX) COLLATE Latin1_General_CI_AS NULL,
	SITUACAO_NIVEL1 bigint NULL,
	SITUACAO_NIVEL2 bigint NULL,
	SITUACAO_NIVEl3 bigint NULL,
	SITUACAO_NIVEL4 float NULL,
	SITUACAO_NIVEL5 bigint NULL,
	SITUACAO_NIVEL6 float NULL,
	CPF_RESPONSAVEL float NULL,
	NOME_RESPONSAVEL varchar(MAX) COLLATE Latin1_General_CI_AS NULL,
	EMAIL_RESPONSAVEL varchar(MAX) COLLATE Latin1_General_CI_AS NULL,
	CONSTRAINT FORNECEDOR_COMPLEMENTO_PK_{0} PRIMARY KEY (ID_FORN_SICAF)
)
""".format(id_code)

_SERVIDOR = """
CREATE TABLE seges_cgial_fornecedor.dbo._SERVIDOR (
	ID_SERVIDOR varchar(18) COLLATE Latin1_General_CI_AS NOT NULL,
	NO_SERVIDOR varchar(255) COLLATE Latin1_General_CI_AS NULL,
	LOTACAO varchar(255) COLLATE Latin1_General_CI_AS NULL,
	CARGO varchar(255) COLLATE Latin1_General_CI_AS NULL,
	DT_CONSULTA_SERVIDOR date NULL,
	CONSTRAINT SERVIDOR_PK_{0} PRIMARY KEY (ID_SERVIDOR)
)
""".format(id_code)


_FORNECEDOR_SOCIO = """
CREATE TABLE seges_cgial_fornecedor.dbo._FORNECEDOR_SOCIO (
	ID_FORNECEDOR varchar(18) COLLATE Latin1_General_CI_AS NULL,
	NO_FORNECEDOR varchar(255) COLLATE Latin1_General_CI_AS NULL,
	ID_FORNECEDOR_PROPRIETARIO varchar(18) COLLATE Latin1_General_CI_AS NULL,
	TP_VINCULO_FORNECEDOR int NULL,
	SOCIO varchar(18) COLLATE Latin1_General_CI_AS NULL
);
CREATE NONCLUSTERED INDEX FORNECEDOR_SOCIO_ID_FORNECEDOR_IDX_{0} ON dbo._FORNECEDOR_SOCIO (  ID_FORNECEDOR ASC  , SOCIO ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [SECONDARY ];
""".format(id_code)

_SOCIO = """
CREATE TABLE seges_cgial_fornecedor.dbo._SOCIO (
	SOCIO varchar(50) COLLATE Latin1_General_CI_AS NULL,
	ID_SOCIO varchar(50) COLLATE Latin1_General_CI_AS NULL,
	NO_SOCIO varchar(255) COLLATE Latin1_General_CI_AS NULL,
	PAI_SOCIO varchar(50) COLLATE Latin1_General_CI_AS NULL,
	GRUPO varchar(255) COLLATE Latin1_General_CI_AS NULL,
	TP_SOCIO int NULL,
	NUM_PARTICIPACAO_ACIONARIA float NULL
);
CREATE NONCLUSTERED INDEX SOCIO_ID_SOCIO_IDX_{0} ON dbo._SOCIO (  ID_SOCIO ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [SECONDARY ];
""".format(id_code)

_FORNECEDOR_PENALIDADE ="""
CREATE TABLE seges_cgial_fornecedor.dbo._FORNECEDOR_PENALIDADE (
	ID_FORNECEDOR varchar(50) COLLATE Latin1_General_CI_AS NULL,
	ORIGEM varchar(5) COLLATE Latin1_General_CI_AS NULL,
	TIPO varchar(300) COLLATE Latin1_General_CI_AS NULL,
	DT_INICIO datetime2(7) NULL,
	DT_FINAL datetime2(7) NULL,
	DESCRICAO nvarchar(2000) COLLATE Latin1_General_CI_AS NULL,
	UASG bigint NULL,
	ORGAO_SANCIONADOR nvarchar(300) COLLATE Latin1_General_CI_AS NULL,
	DETALHE nvarchar(2000) COLLATE Latin1_General_CI_AS NULL
);
CREATE CLUSTERED INDEX FORNECEDORPENALIDADE_IDX_PENALIDADE_{0} ON dbo._FORNECEDOR_PENALIDADE (  ID_FORNECEDOR ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [SECONDARY ];
""".format(id_code)

_FORNECEDOR_INDICADORES = """
CREATE TABLE seges_cgial_fornecedor.dbo._FORNECEDOR_INDICADORES (
	ID_FORNECEDOR varchar(18) COLLATE Latin1_General_CI_AS NOT NULL,
	ORDEM int NOT NULL,
	ATRIBUTO varchar(200) COLLATE Latin1_General_CI_AS NULL,
	VALOR varchar(200) COLLATE Latin1_General_CI_AS NULL,
	OBSERVACAO varchar(MAX) COLLATE Latin1_General_CI_AS NULL,
	ICONE int NULL,
	STATUS int NULL,
	CONSTRAINT FORNECEDOR_INDICADORES_PK_{0} PRIMARY KEY (ID_FORNECEDOR,ORDEM)
)
""".format(id_code)


_FORNECEDOR_PENALIDADE_SOCIO = """
CREATE TABLE seges_cgial_fornecedor.dbo._FORNECEDOR_PENALIDADE_SOCIO (
	ID_FORNECEDOR varchar(50) COLLATE Latin1_General_CI_AS NOT NULL,
	QTD_VIGENTE int NULL,
	QTD_VENCIDA int NULL,
	CONSTRAINT FORNECEDOR_PENALIDADE_SOCIO_PK_{0} PRIMARY KEY (ID_FORNECEDOR)
)
""".format(id_code)

_FORNECEDOR_PENALIDADE_FORN = """
CREATE TABLE seges_cgial_fornecedor.dbo._FORNECEDOR_PENALIDADE_FORN (
	ID_FORNECEDOR varchar(50) COLLATE Latin1_General_CI_AS NOT NULL,
	QTD_VIGENTE int NULL,
	QTD_VENCIDA int NULL,
	CONSTRAINT FORNECEDOR_PENALIDADE_FORN_PK_{0} PRIMARY KEY (ID_FORNECEDOR)
)
""".format(id_code)


INDICES = """
CREATE NONCLUSTERED INDEX IX_FORNECEDOR_NO_FORNECEDOR ON FORNECEDOR (NO_FORNECEDOR);
CREATE NONCLUSTERED INDEX IX_FORNECEDOR_NU_CNPJ_CPF ON FORNECEDOR (NU_CNPJ_CPF);
CREATE NONCLUSTERED INDEX IX_SOCIO_ID ON SOCIO (ID_SOCIO);
CREATE NONCLUSTERED INDEX IX_SOCIO_SOCIO ON SOCIO (SOCIO);
CREATE NONCLUSTERED INDEX IX_FORNECEDOR_SOCIO_ID_FOR_SOCIO ON FORNECEDOR_SOCIO (ID_FORNECEDOR, SOCIO);
CREATE NONCLUSTERED INDEX IX_FORNECEDOR_SOCIO_ID_PROPRIETARIO ON FORNECEDOR_SOCIO (ID_FORNECEDOR_PROPRIETARIO);
CREATE NONCLUSTERED INDEX IX_FORNECEDOR_SOCIO_SOCIO ON FORNECEDOR_SOCIO (SOCIO);
CREATE NONCLUSTERED INDEX IX_FORNECEDOR_COMPLEMENTO_ID_PESSOA ON FORNECEDOR_COMPLEMENTO (ID_PESSOA);
CREATE NONCLUSTERED INDEX IX_FORNECEDOR_PENALIDADE_ID_FOR ON  FORNECEDOR_PENALIDADE (ID_FORNECEDOR);
CREATE NONCLUSTERED INDEX IX_FORNECEDOR_PENALIDADE_UASG ON  FORNECEDOR_PENALIDADE (UASG);
CREATE NONCLUSTERED INDEX IX_FORNECEDOR_PROPRIETARIO_ID_FOR ON FORNECEDOR_PROPRIETARIO (ID_FORNECEDOR_PROPRIETARIO);
CREATE NONCLUSTERED INDEX IX_FORNECEDOR_PROPRIETARIO_NOME ON FORNECEDOR_PROPRIETARIO (NO_FORNECEDOR_PROPRIETARIO);
CREATE NONCLUSTERED INDEX IX_PESSOA_ID ON PESSOA (id_pessoa);
CREATE NONCLUSTERED INDEX IX_PESSOA_CPF_CNPJ ON PESSOA (num_cpf_cnpj);
"""