# -*- coding: utf-8 -*-
from datetime import datetime
id_code = str(datetime.now())
id_code = id_code.replace('-','').replace(':','').replace('.','').replace(' ','')

DROP_TABLE = """
DROP TABLE IF EXISTS seges_cgial_fornecedor.dbo._FORNECEDOR_COMPORTAMENTO;
DROP TABLE IF EXISTS seges_cgial_fornecedor.dbo._FORNECEDOR_CONTRATO;
DROP TABLE IF EXISTS seges_cgial_fornecedor.dbo._FORNECEDOR_CONTRATO_ITEM;
DROP TABLE IF EXISTS seges_cgial_fornecedor.dbo._FORNECEDOR_HISTORICO;
DROP TABLE IF EXISTS seges_cgial_fornecedor.dbo._FORNECEDOR_HISTORICO_CONTRATO;
DROP TABLE IF EXISTS seges_cgial_fornecedor.dbo._FORNECEDOR_SUMARIO_COMPRA;
"""


_FORNECEDOR_COMPORTAMENTO =  """
CREATE TABLE seges_cgial_fornecedor.dbo._FORNECEDOR_COMPORTAMENTO (
	ID_FORNECEDOR varchar(28) COLLATE Latin1_General_CI_AS NOT NULL,
	ORDEM int NOT NULL,
	ATRIBUTO varchar(300) COLLATE Latin1_General_CI_AS NULL,
	VALOR varchar(MAX) COLLATE Latin1_General_CI_AS NULL,
	OBSERVACAO varchar(MAX) COLLATE Latin1_General_CI_AS NULL,
	STATUS int NULL,
	CONSTRAINT FORNECEDOR_COMPORTAMENTO_PK_{0} PRIMARY KEY (ID_FORNECEDOR,ORDEM)
);
""".format(id_code)

_FORNECEDOR_CONTRATO="""
CREATE TABLE seges_cgial_fornecedor.dbo._FORNECEDOR_CONTRATO (
	ID_CNTR_CONTRATO float NOT NULL,
	ID_CMPR_COMPRA float NOT NULL,
	ID_FRND_FORNECEDOR_CONTRATO varchar(50) COLLATE Latin1_General_CI_AS NULL,
	ID_UNDD_UNID_PARTICIPANTE_CONTRATO float NULL,
	NO_FRND_FORNECEDOR_CONTRATO varchar(300) COLLATE Latin1_General_CI_AS NULL,
	NO_UNDD_UNID_PARTICIPANTE_CONTRATO varchar(300) COLLATE Latin1_General_CI_AS NULL,
	NO_MODALIDADE_COMPRA varchar(100) COLLATE Latin1_General_CI_AS NULL,
	VL_CNTR_INICIAL_CONTRATO float NULL,
	VL_CNTR_FINAL_CONTRATO float NULL,
	CH_CNTR_IDENT_CONTRATO_EDIT varchar(100) COLLATE Latin1_General_CI_AS NULL,
	ID_CNTR_IN_EXEC_CONT float NULL,
	DS_CNTR_OBJ_CONT varchar(2000) COLLATE Latin1_General_CI_AS NULL,
	DT_CNTR_ASS_CONT datetime NULL,
	DT_CNTR_INICIO_VIGENCIA datetime NULL,
	DT_CNTR_FIM_VIGENCIA datetime NULL,
	CONSTRAINT FORNECEDOR_CONTRATO_PK_{0} PRIMARY KEY (ID_CNTR_CONTRATO)
)
""".format(id_code)

_FORNECEDOR_CONTRATO_ITEM = """
CREATE TABLE seges_cgial_fornecedor.dbo._FORNECEDOR_CONTRATO_ITEM (
	ID_CNTR_CONTRATO float NULL,
	ID_ITCT_ITEM_CONTRATO float NOT NULL,
	ID_ITCP_ITEM_COMPRA float NULL,
	CH_ITCT_ITEM_CONTRATO_EDIT varchar(44) COLLATE Latin1_General_CI_AS NULL,
	NO_ITCP_ITEM_CONTRATO varchar(240) COLLATE Latin1_General_CI_AS NULL,
	ID_ITCP_TP_COD_MAT_SERV float NULL,
	NO_ITCP_TP_COD_MAT_SERV varchar(300) COLLATE Latin1_General_CI_AS NULL,
	QT_ITCT_ITENS_CONTRATO float NULL,
	QT_ITCT_CONTRATADA float NULL,
	VL_ITCT_CONTRATADO float NULL,
	CONSTRAINT PK_CONTRATO_ITEM_{0} PRIMARY KEY (ID_ITCT_ITEM_CONTRATO)
);
""".format(id_code)


_FORNECEDOR_HISTORICO = """
CREATE TABLE seges_cgial_fornecedor.dbo._FORNECEDOR_HISTORICO (
	ID_FORNECEDOR varchar(28) COLLATE Latin1_General_CI_AS NOT NULL,
	ORDEM int NOT NULL,
	ATRIBUTO varchar(300) COLLATE Latin1_General_CI_AS NULL,
	VALOR int NULL,
	OBSERVACAO varchar(2000) COLLATE Latin1_General_CI_AS NULL,
	STATUS int NULL,
	CONSTRAINT PK_FORNECEDOR_HISTORICO_{0} PRIMARY KEY (ID_FORNECEDOR,ORDEM)
);
""".format(id_code)

_FORNECEDOR_HISTORICO_CONTRATO = """
CREATE TABLE seges_cgial_fornecedor.dbo._FORNECEDOR_HISTORICO_CONTRATO (
	ID_FORNECEDOR varchar(28) COLLATE Latin1_General_CI_AS NOT NULL,
	ORDEM int NOT NULL,
	ATRIBUTO varchar(300) COLLATE Latin1_General_CI_AS NULL,
	VALOR int NULL,
	OBSERVACAO varchar(2000) COLLATE Latin1_General_CI_AS NULL,
	STATUS int NULL,
	CONSTRAINT PK_FORNECEDOR_HISTORICO_CONTRATO_{0} PRIMARY KEY (ID_FORNECEDOR,ORDEM)
)
""".format(id_code)

_FORNECEDOR_SUMARIO_COMPRA ="""
CREATE TABLE seges_cgial_fornecedor.dbo._FORNECEDOR_SUMARIO_COMPRA (
	ID_FORNECEDOR varchar(28) COLLATE Latin1_General_CI_AS NOT NULL,
	QTD_COMPRA float NULL,
	QTD_ITEM_COMPRA float NULL,
	QTD_COMPRA_HOMOLOG float NULL,
	QTD_ITEM_COMPRA_HOMOLOG float NULL,
	VALOR_HOMOLOGADO float NULL,
	CONSTRAINT FORNECEDOR_SUMARIO_COMPRA_PK_{0} PRIMARY KEY (ID_FORNECEDOR)
);
""".format(id_code)


INDICES = """
CREATE NONCLUSTERED INDEX IX_FORNECEDOR_CONTRATO_ID_CMPR_COMPRA ON FORNECEDOR_CONTRATO (ID_CMPR_COMPRA);
CREATE NONCLUSTERED INDEX IX_FORNECEDOR_CONTRATO_ID_FRND ON FORNECEDOR_CONTRATO (ID_FRND_FORNECEDOR_CONTRATO);
CREATE NONCLUSTERED INDEX IX_FORNECEDOR_CONTRATO_ID_UNDD_UNID ON FORNECEDOR_CONTRATO (ID_UNDD_UNID_PARTICIPANTE_CONTRATO);
CREATE NONCLUSTERED INDEX IX_FORNECEDOR_CONTRATO_CH_CNTR ON FORNECEDOR_CONTRATO (CH_CNTR_IDENT_CONTRATO_EDIT);
CREATE NONCLUSTERED INDEX IX_FORNECEDOR_CONTRATO_ITEM_ID_CONTRATO ON FORNECEDOR_CONTRATO_ITEM (ID_CNTR_CONTRATO);
"""