CREATE TABLE dbo.Dados_CNEP(
	ID int NOT NULL,
	DATA_REFERENCIA varchar(15) NULL,
	DATA_INICIO_SANCAO varchar(15) NULL,
	DATA_FIM_SANCAO varchar(15) NULL,
	DATA_TRAN_JULGADO varchar(15) NULL,
	DATA_ORIGEM_INFO varchar(15) NULL,
	VALOR_MULTA varchar(15) NULL,
	TEXTO_PUBLICACAO varchar(500) NULL,
	LINK_PUBLICACAO varchar(200) NULL,
	DETALHAMENTO_PUBLICACAO varchar(500) NULL,
	NUMERO_PROCESSO varchar(50) NULL,
	ABRANG_DEF_DEC_JUDICIAL varchar(50) NULL,
	INFO_ORG_SANCIONADOR varchar(100) NULL,
 CONSTRAINT PK_Dados_CNEP PRIMARY KEY CLUSTERED (ID ASC));


CREATE TABLE dbo.FONTE_SANCAO(
	ID int NOT NULL,
	NOME_EXIBICAO varchar(100) NULL,
	TELEFONE_CONTATO varchar(20) NULL,
	ENDERECO_CONTATO varchar(200) NULL);




CREATE TABLE dbo.LEGISLACAO(
	ID int NOT NULL,
	FUND_LEGAL varchar(500) NULL,
	DESC_FUND_LEGAL varchar(550) NULL);


CREATE TABLE dbo.ORGAO_SANCIONADOR(
	ID int NOT NULL,
	NOME varchar(100) NULL,
	SIGLA_UF varchar(2) NULL,
	PODER varchar(100) NULL);

ALTER TABLE dbo.ORGAO_SANCIONADOR  WITH CHECK ADD  CONSTRAINT FK_ORGAO_SANCIONADOR_Dados_CNEP FOREIGN KEY(ID)
REFERENCES dbo.Dados_CNEP (ID);

ALTER TABLE dbo.ORGAO_SANCIONADOR CHECK CONSTRAINT FK_ORGAO_SANCIONADOR_Dados_CNEP





CREATE TABLE dbo.PESSOA(
	ID int NOT NULL,
	NUMERO_INSC_SOCIAL varchar(100) NULL,
	NOME varchar(200) NULL,
	RAZAO_SOCIAL_RECEITA varchar(200) NULL,
	NOME_FANTASIA varchar(100) NULL,
	CODIGO_SECAO varchar(50) NULL,
	SECAO varchar(60) NULL,
	COD_SUB_CLASSE varchar(100) NULL,
	SUB_CLASSE varchar(200) NULL,
	COD_DIVISAO varchar(50) NULL,
	LOCALIDADE varchar(100) NULL,
	DATA_ABERTURA varchar(50) NULL,
	END_ELETRONICO varchar(100) NULL,
	NUMERO_TELEFONE varchar(50) NULL,
	DESC_LOGRADOURO varchar(100) NULL,
	NUMERO_ENDERECO varchar(50) NULL,
	COMPLEMENTO_ENDERECO varchar(100) NULL,
	NUMERO_CEP varchar(50) NULL,
	NOME_BAIRRO varchar(100) NULL,
	COD_FOMATADO varchar(50) NULL,
	TIPO_CODIGO varchar(50) NULL,
	TIPO_PESSOA varchar(50) NULL);





CREATE TABLE dbo.PESSOA_CNAE(
	ID int NOT NULL,
	NUMERO_INSC_SOCIAL varchar(100) NULL,
	DIVISAO varchar(200) NULL,
	COD_GRUPO varchar(100) NULL,
	GRUPO varchar(500) NULL,
	COD_CLASSE varchar(100) NULL,
	CLASSE varchar(500) NULL);

ALTER TABLE dbo.PESSOA_CNAE  WITH CHECK ADD  CONSTRAINT FK_PESSOA_CNAE_Dados_CNEP FOREIGN KEY(ID)
REFERENCES dbo.Dados_CNEP (ID);

ALTER TABLE dbo.PESSOA_CNAE CHECK CONSTRAINT FK_PESSOA_CNAE_Dados_CNEP;





CREATE TABLE dbo.PESSOA_MUNICIPIO(
	ID int NOT NULL,
	NUMERO_INSC_SOCIAL varchar(100) NULL,
	COD_IBGE int NULL,
	NOME_IBGE varchar(50) NULL,
	PAIS varchar(50) NULL,
	SIGLA_UF varchar(2) NULL,
	NOME_UF varchar(50) NULL);

ALTER TABLE dbo.PESSOA_MUNICIPIO  WITH CHECK ADD  CONSTRAINT FK_PESSOA_MUNICIPIO_Dados_CNEP FOREIGN KEY(ID)
REFERENCES dbo.Dados_CNEP (ID);

ALTER TABLE dbo.PESSOA_MUNICIPIO CHECK CONSTRAINT FK_PESSOA_MUNICIPIO_Dados_CNEP;





CREATE TABLE dbo.PESSOA_NATUREZA_JURIDICA(
	ID int NOT NULL,
	NUMERO_INSC_SOCIAL varchar(100) NULL,
	CODIGO varchar(10) NULL,
	DESCRICAO varchar(100) NULL,
	COD_TIPO varchar(10) NULL,
	DESC_TIPO varchar(100) NULL);

ALTER TABLE dbo.PESSOA_NATUREZA_JURIDICA  WITH CHECK ADD  CONSTRAINT FK_PESSOA_NATUREZA_JURIDICA_Dados_CNEP FOREIGN KEY(ID)
REFERENCES dbo.Dados_CNEP (ID);

ALTER TABLE dbo.PESSOA_NATUREZA_JURIDICA CHECK CONSTRAINT FK_PESSOA_NATUREZA_JURIDICA_Dados_CNEP;





CREATE TABLE dbo.SANCIONADO(
	ID int NOT NULL,
	NOME varchar(100) NULL,
	COD_FORMATADO varchar(20) NULL);

ALTER TABLE dbo.SANCIONADO  WITH CHECK ADD  CONSTRAINT FK_SANCIONADO_Dados_CNEP FOREIGN KEY(ID)
REFERENCES dbo.Dados_CNEP (ID);

ALTER TABLE dbo.SANCIONADO CHECK CONSTRAINT FK_SANCIONADO_Dados_CNEP;







CREATE TABLE dbo.TIPO_SANCAO(
	ID int NOT NULL,
	DESC_RESUMIDA varchar(200) NULL,
	DESC_PORTAL varchar(100) NULL);

ALTER TABLE dbo.TIPO_SANCAO  WITH CHECK ADD  CONSTRAINT FK_TIPO_SANCAO_Dados_CNEP FOREIGN KEY(ID)
REFERENCES dbo.Dados_CNEP (ID);

ALTER TABLE dbo.TIPO_SANCAO CHECK CONSTRAINT FK_TIPO_SANCAO_Dados_CNEP;