CREATE TABLE Dados_inadimplentes (
    TIPO_MEDIDA VARCHAR(25),
    PODER VARCHAR(20),
    SECRETARIA_ORG VARCHAR(50),
    UGE VARCHAR(50),
    NUMERO_PROCESSO VARCHAR(200),
    TIPO_PESSOA VARCHAR(10),
    RAZAO_SOCIAL VARCHAR(200),
    CNPJ_CPF VARCHAR(15),
    TIPO_SANCAO VARCHAR(40),
    PERIOD_SANCAO VARCHAR(20),
    DATA_INICIO VARCHAR(15),
    DATA_TERMINO VARCHAR(15),
    ABRANGENCIA_PENALIDADE VARCHAR(200),
    VALOR_MULTA VARCHAR(20)
);

CREATE INDEX IDX_Dados_Inadimplentes ON Dados_inadimplentes(CNPJ_CPF);