CREATE TABLE Dados_CEPIM
(
CNPJ_ENTIDADE VARCHAR(14),
NOME_ENTIDADE VARCHAR(250),
NUMERO_CONVENIO VARCHAR(50),
ORGAO_CONCEDENTE VARCHAR(250),
MOTIVO_IMPEDIMENTO VARCHAR(500));


CREATE INDEX IDX_DADOS_CEPIM ON DADOS_CEPIM (CNPJ_ENTIDADE,NOME_ENTIDADE);