CREATE TABLE dbo.Dados_Leniencia(
CNPJ VARCHAR(18) NULL, 
DATA_FIM_ACORDO VARCHAR(10) NULL, 
DATA_INICIO_ACORDO VARCHAR(10) NULL, 
ID INT, NOME_EMPRESA VARCHAR(200) NULL,
ORGAO_RESPONSAVEL VARCHAR(200) NULL, 
NOME_FANTASIA VARCHAR(200) NULL, 
QUANTIDADE INT NULL, 
RAZAO_SOCIAL VARCHAR(200) NULL, 
SITUACAO_ACORDO VARCHAR(100) NULL, 
UF_EMPRESA VARCHAR(2) NULL); 

CREATE INDEX IDX_DadosLeniencia on dbo.Dados_Leniencia(CNPJ);