CREATE TABLE dbo.Dados_Leniencia
(
CNPJ VARCHAR(18),
DATA_FIM_ACORDO VARCHAR(10),
DATA_INICIO_ACORDO VARCHAR(10),
ID INT,
NOME_EMPRESA VARCHAR(200),
ORGAO_RESPONSAVEL VARCHAR(200),
NOME_FANTASIA VARCHAR(200),
QUANTIDADE INT,
RAZAO_SOCIAL VARCHAR(200),
SITUACAO_ACORDO VARCHAR(100),
UF_EMPRESA VARCHAR(2)
 );
CREATE INDEX IDX_DadosLeniencia on dbo.Dados_Leniencia(CNPJ);